export type SFRColorValue =
  'color-primary-10' |
  'color-primary-20' |
  'color-primary-30' |
  'color-primary-40' |
  'color-primary-50' |
  'color-primary' |
  'color-primary-60' |
  'color-primary-70' |
  'color-primary-80' |
  'color-primary-90' |
  'color-grey-00' |
  'color-grey-10' |
  'color-grey-20' |
  'color-grey-30' |
  'color-grey-40' |
  'color-grey-50' |
  'color-grey' |
  'color-grey-60' |
  'color-grey-70' |
  'color-grey-80' |
  'color-grey-90' |
  'color-grey-100' |
  'color-secondary-10' |
  'color-secondary-20' |
  'color-secondary-30' |
  'color-secondary-40' |
  'color-secondary-50' |
  'color-secondary' |
  'color-secondary-60' |
  'color-secondary-70' |
  'color-secondary-80' |
  'color-secondary-90';

export type SFRTypeValue =
  'type-text-100' |
  'type-text-100-size' |
  'type-text-100-weight' |
  'type-text-90' |
  'type-text-90-size' |
  'type-text-90-weight' |
  'type-text-80' |
  'type-text-80-size' |
  'type-text-80-weight' |
  'type-text-70' |
  'type-text-70-size' |
  'type-text-70-weight' |
  'type-text-60' |
  'type-text-60-size' |
  'type-text-60-weight' |
  'type-text-50' |
  'type-text-50-size' |
  'type-text-50-weight' |
  'type-text' |
  'type-text-size' |
  'type-text-weight' |
  'type-text-40' |
  'type-text-40-size' |
  'type-text-40-weight' |
  'type-text-30' |
  'type-text-30-size' |
  'type-text-30-weight' |
  'type-text-20' |
  'type-text-20-size' |
  'type-text-20-weight' |
  'type-text-10' |
  'type-text-10-size' |
  'type-text-10-weight' |
  'type-text-bold-100' |
  'type-text-bold-100-size' |
  'type-text-bold-100-weight' |
  'type-text-bold-90' |
  'type-text-bold-90-size' |
  'type-text-bold-90-weight' |
  'type-text-bold-80' |
  'type-text-bold-80-size' |
  'type-text-bold-80-weight' |
  'type-text-bold-70' |
  'type-text-bold-70-size' |
  'type-text-bold-70-weight' |
  'type-text-bold-60' |
  'type-text-bold-60-size' |
  'type-text-bold-60-weight' |
  'type-text-bold-50' |
  'type-text-bold-50-size' |
  'type-text-bold-50-weight' |
  'type-text-bold' |
  'type-text-bold-size' |
  'type-text-bold-weight' |
  'type-text-bold-40' |
  'type-text-bold-40-size' |
  'type-text-bold-40-weight' |
  'type-text-bold-30' |
  'type-text-bold-30-size' |
  'type-text-bold-30-weight' |
  'type-text-bold-20' |
  'type-text-bold-20-size' |
  'type-text-bold-20-weight' |
  'type-text-bold-10' |
  'type-text-bold-10-size' |
  'type-text-bold-10-weight' |
  'type-text-semibold-100' |
  'type-text-semibold-100-size' |
  'type-text-semibold-100-weight' |
  'type-text-semibold-90' |
  'type-text-semibold-90-size' |
  'type-text-semibold-90-weight' |
  'type-text-semibold-80' |
  'type-text-semibold-80-size' |
  'type-text-semibold-80-weight' |
  'type-text-semibold-70' |
  'type-text-semibold-70-size' |
  'type-text-semibold-70-weight' |
  'type-text-semibold-60' |
  'type-text-semibold-60-size' |
  'type-text-semibold-60-weight' |
  'type-text-semibold-50' |
  'type-text-semibold-50-size' |
  'type-text-semibold-50-weight' |
  'type-text-semibold' |
  'type-text-semibold-size' |
  'type-text-semibold-weight' |
  'type-text-semibold-40' |
  'type-text-semibold-40-size' |
  'type-text-semibold-40-weight' |
  'type-text-semibold-30' |
  'type-text-semibold-30-size' |
  'type-text-semibold-30-weight' |
  'type-text-semibold-20' |
  'type-text-semibold-20-size' |
  'type-text-semibold-20-weight' |
  'type-text-semibold-10' |
  'type-text-semibold-10-size' |
  'type-text-semibold-10-weight';

export type SFRSpacingValue =
  'spacing-0' |
  'spacing-0-3' |
  'spacing-0-6' |
  'spacing-0-9' |
  'spacing-1' |
  'spacing-1-3' |
  'spacing-1-6' |
  'spacing-1-9' |
  'spacing-2' |
  'spacing-3' |
  'spacing-4' |
  'spacing-5' |
  'spacing-6' |
  'spacing-7' |
  'spacing-8' |
  'spacing-col-0' |
  'spacing-col-0-3' |
  'spacing-col-0-4' |
  'spacing-col-0-6' |
  'spacing-col-0-8' |
  'spacing-col-0-9' |
  'spacing-col-1' |
  'spacing-col-1-3' |
  'spacing-col-1-4' |
  'spacing-col-1-6' |
  'spacing-col-1-8' |
  'spacing-col-1-9' |
  'spacing-col-2' |
  'spacing-col-2-3' |
  'spacing-col-2-4' |
  'spacing-col-2-6' |
  'spacing-col-2-8' |
  'spacing-col-2-9' |
  'spacing-col-3' |
  'spacing-col-3-3' |
  'spacing-col-3-4' |
  'spacing-col-3-6' |
  'spacing-col-3-8' |
  'spacing-col-3-9' |
  'spacing-col-4' |
  'spacing-col-5' |
  'spacing-col-6' |
  'spacing-col-7' |
  'spacing-col-8' |
  'spacing-col-9' |
  'spacing-col-10' |
  'spacing-col-11' |
  'spacing-col-12' |
  'spacing-colvw-0' |
  'spacing-colvw-0-3' |
  'spacing-colvw-0-4' |
  'spacing-colvw-0-6' |
  'spacing-colvw-0-8' |
  'spacing-colvw-0-9' |
  'spacing-colvw-1' |
  'spacing-colvw-1-3' |
  'spacing-colvw-1-4' |
  'spacing-colvw-1-6' |
  'spacing-colvw-1-8' |
  'spacing-colvw-1-9' |
  'spacing-colvw-2' |
  'spacing-colvw-2-3' |
  'spacing-colvw-2-4' |
  'spacing-colvw-2-6' |
  'spacing-colvw-2-8' |
  'spacing-colvw-2-9' |
  'spacing-colvw-3' |
  'spacing-colvw-3-3' |
  'spacing-colvw-3-4' |
  'spacing-colvw-3-6' |
  'spacing-colvw-3-8' |
  'spacing-colvw-3-9' |
  'spacing-colvw-4' |
  'spacing-colvw-5' |
  'spacing-colvw-6' |
  'spacing-colvw-7' |
  'spacing-colvw-8' |
  'spacing-colvw-9' |
  'spacing-colvw-10' |
  'spacing-colvw-11' |
  'spacing-colvw-12';

export type SFREffectValue =
  'effect-shadow-shadow';

export type SFRValue =
  SFRColorValue |
  SFRTypeValue |
  SFRSpacingValue |
  SFREffectValue;
